name: Cypress Tests

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Start JSON Server
        run: npx json-server --watch server/db.json --port 3001 &

      - name: Start React App
        run: npm run dev &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:5173, http://localhost:3001'
          wait-on-timeout: 60
          browser: chrome